-- MySQL Script generated by MySQL Workbench
-- Sun Oct 16 00:17:16 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema e_commerce_ref
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema e_commerce_ref
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `e_commerce_ref` DEFAULT CHARACTER SET utf8 ;
USE `e_commerce_ref` ;

-- -----------------------------------------------------
-- Table `e_commerce_ref`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e_commerce_ref`.`Clientes` (
  `idClient` INT NOT NULL AUTO_INCREMENT COMMENT 'id do cliente é do tipo único e auto incrementável.',
  `Pname` VARCHAR(10) NOT NULL COMMENT 'Correponde ao primeiro nome do clieinte é um dipo caractere obrigatório.',
  `Minit` CHAR(3) NULL COMMENT 'Corresponde a inicial do nome do meio é do tipo char(3).',
  `Lname` VARCHAR(20) NOT NULL COMMENT 'Corresponde ao Sobrenome do cliente, campo tipo caractere obrigatório.',
  `Address` VARCHAR(100) NOT NULL COMMENT 'Endereço do cliente, campo deve ser obrigatório.',
  `phone` VARCHAR(15) NOT NULL COMMENT 'Telefone do cliente, o campo deve ser do tipo caractare e obrigatório.',
  PRIMARY KEY (`idClient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e_commerce_ref`.`Entregas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e_commerce_ref`.`Entregas` (
  `idDeliver` INT NOT NULL AUTO_INCREMENT COMMENT 'id de entrega - auto incremento e chave primaria.',
  `Cod` INT NOT NULL COMMENT 'Códido do rastreio da empresa que irá efetuar a logistica.',
  `Status` ENUM('Aguardando', 'Em preparação', 'Enviado', 'Em trânsito', 'Saiu para entrega', 'Entregue') NOT NULL DEFAULT 'Aguardando' COMMENT 'Status da entrega.(\'Aguardando\',\'Em preparação\', \'Enviado\', \'Em trânsito\', \'Saiu para entrega\', \'Entregue\') com padrão \'Aguardando\'',
  `ShippingValue` FLOAT NOT NULL DEFAULT 0 COMMENT 'Valor do frete, por padrão 0.00 - tipo float e not null.',
  PRIMARY KEY (`idDeliver`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e_commerce_ref`.`CreditCards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e_commerce_ref`.`CreditCards` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL COMMENT 'Nome do Titular do cartão.\n',
  `Number` VARCHAR(15) NOT NULL COMMENT 'Número do cartão - deve ser do tipo único.',
  `Flag` VARCHAR(45) NOT NULL COMMENT 'Bandeira - visa, master etc...',
  `ExpirationDate` DATE NOT NULL COMMENT 'Data de validade',
  `fk_idClient` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Number_UNIQUE` (`Number` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Pagamentos_Clientes1_idx` (`fk_idClient` ASC) VISIBLE,
  CONSTRAINT `fk_Pagamentos_Clientes1`
    FOREIGN KEY (`fk_idClient`)
    REFERENCES `e_commerce_ref`.`Clientes` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e_commerce_ref`.`Formas_Pagamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e_commerce_ref`.`Formas_Pagamentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `PayType` VARCHAR(45) NOT NULL DEFAULT 'Pix' COMMENT 'Tipo de Pagamento. Padrão Pix.\nex: Cartão, Boleto, Débito.',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `PayType_UNIQUE` (`PayType` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e_commerce_ref`.`Pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e_commerce_ref`.`Pedidos` (
  `idOrder` INT NOT NULL AUTO_INCREMENT COMMENT 'id do produto, tipo chave primária auto increment.',
  `fk_idClient` INT NOT NULL COMMENT 'Chave estrangeira da tabala cliente (idClient).',
  `fk_idDeliver` INT NOT NULL,
  `fk_idPayType` INT NOT NULL,
  `fk_idCreditCard` INT NULL,
  `Status` ENUM('Cancelado', 'Confirmado', 'Em processamento') NOT NULL DEFAULT 'Em Processamento' COMMENT 'Status do pedido pode ser: \'Cancelado\', \'Confirmado\', \'Em processamento\'.\nPor Padrão: \"Em processamento\".',
  `Description` VARCHAR(255) NULL COMMENT 'Descrição do produto, campo não é obrigatório.',
  `TotalValue` FLOAT NOT NULL COMMENT 'Valor total do pedido. tipo float, valor padrão  não pose se nulo.',
  `Date` DATE NOT NULL COMMENT 'Data do pedido, tipo datetime()',
  `NumberPayment` VARCHAR(45) NOT NULL COMMENT 'Corresponde ao registro da forma de pagamento, seja boleto, débito ou cartão de crédito.',
  PRIMARY KEY (`idOrder`, `fk_idClient`, `fk_idDeliver`),
  INDEX `fk_Pedido_Cliente1_idx` (`fk_idClient` ASC) VISIBLE,
  INDEX `fk_Pedidos_Entregas1_idx` (`fk_idDeliver` ASC) VISIBLE,
  INDEX `fk_Pedidos_CreditCards1_idx` (`fk_idCreditCard` ASC) VISIBLE,
  INDEX `fk_Pedidos_Formas_Pagamentos1_idx` (`fk_idPayType` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Cliente1`
    FOREIGN KEY (`fk_idClient`)
    REFERENCES `e_commerce_ref`.`Clientes` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedidos_Entregas1`
    FOREIGN KEY (`fk_idDeliver`)
    REFERENCES `e_commerce_ref`.`Entregas` (`idDeliver`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedidos_CreditCards1`
    FOREIGN KEY (`fk_idCreditCard`)
    REFERENCES `e_commerce_ref`.`CreditCards` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedidos_Formas_Pagamentos1`
    FOREIGN KEY (`fk_idPayType`)
    REFERENCES `e_commerce_ref`.`Formas_Pagamentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e_commerce_ref`.`Produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e_commerce_ref`.`Produtos` (
  `idProduct` INT NOT NULL AUTO_INCREMENT COMMENT 'Chave primária do tipo auto incremento.',
  `Name` VARCHAR(20) NOT NULL COMMENT 'Nome do produto, campo obrigatório.',
  `ClassKids` TINYINT NOT NULL DEFAULT 0 COMMENT 'Tipo de classificação se True é do tipo kids se false adult, por padrão deixar como false.',
  `Category` ENUM('Eletrônico', 'Vestimenta', 'Brinquedos', 'Alimentos', 'Móveis') NOT NULL COMMENT 'Categoria pode ser: \'Eletrônico\', \'Vestimenta\', \'Brinquedos\', \'Alimentos\', \'Móveis\', não pode ser nulo.',
  `Size` VARCHAR(10) NULL COMMENT 'Tamanho, campo não é obrigatório',
  `Ratings` FLOAT NULL DEFAULT 0 COMMENT 'Avaliações dos clientes. Padrão 0 tipo float',
  `Price` FLOAT NOT NULL,
  PRIMARY KEY (`idProduct`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e_commerce_ref`.`Fornecedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e_commerce_ref`.`Fornecedores` (
  `idSupplier` INT NOT NULL AUTO_INCREMENT COMMENT 'Id do Fornecedor o campo deve ser chave primária e auto incremento.',
  `SocialName` VARCHAR(255) NOT NULL COMMENT 'Razão Social não pode ser nulo.',
  `CNPJ` CHAR(15) NOT NULL COMMENT 'CNPJ da empresa - tipo char(15) não pode ser nulo e dever ser do tipo único.',
  `Contact` CHAR(11) NOT NULL COMMENT 'Telefon - não pode ser nulo.',
  PRIMARY KEY (`idSupplier`),
  UNIQUE INDEX `CNPJ_UNIQUE` (`CNPJ` ASC) VISIBLE,
  UNIQUE INDEX `idFornecedor_UNIQUE` (`idSupplier` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e_commerce_ref`.`Fornecedores/Produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e_commerce_ref`.`Fornecedores/Produtos` (
  `fk_idSupplier` INT NOT NULL COMMENT 'Chave estrangeira da tabela de fornecedores.',
  `fk_idProduct` INT NOT NULL COMMENT 'Chave estrangeira da tabela de produtos.',
  `Quantity` INT NOT NULL COMMENT 'Quantidade em estoque - não nulo.',
  PRIMARY KEY (`fk_idSupplier`, `fk_idProduct`),
  INDEX `fk_Fornecedor_has_Produto_Produto1_idx` (`fk_idProduct` ASC) VISIBLE,
  INDEX `fk_Fornecedor_has_Produto_Fornecedor1_idx` (`fk_idSupplier` ASC) VISIBLE,
  CONSTRAINT `fk_Fornecedor_has_Produto_Fornecedor1`
    FOREIGN KEY (`fk_idSupplier`)
    REFERENCES `e_commerce_ref`.`Fornecedores` (`idSupplier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fornecedor_has_Produto_Produto1`
    FOREIGN KEY (`fk_idProduct`)
    REFERENCES `e_commerce_ref`.`Produtos` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e_commerce_ref`.`Estoques`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e_commerce_ref`.`Estoques` (
  `idStorage` INT NOT NULL AUTO_INCREMENT COMMENT 'id do estoque, tipo auto incremento - chave primárial.',
  `StorageLocation` VARCHAR(255) NOT NULL COMMENT 'Endereço - não pode ser nulo.',
  `Local` VARCHAR(255) NULL DEFAULT 0,
  PRIMARY KEY (`idStorage`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e_commerce_ref`.`Produtos/Estoques`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e_commerce_ref`.`Produtos/Estoques` (
  `fk_idProduct` INT NOT NULL COMMENT 'Chave estrangeira da tabela de produtos.',
  `fk_idStorage` INT NOT NULL COMMENT 'Chave estrangeira da tabela de estoque.',
  `Quantity` INT NOT NULL COMMENT 'Quantidade em estoque.',
  PRIMARY KEY (`fk_idProduct`, `fk_idStorage`),
  INDEX `fk_Produto_has_Estoque_Estoque1_idx` (`fk_idStorage` ASC) VISIBLE,
  INDEX `fk_Produto_has_Estoque_Produto1_idx` (`fk_idProduct` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_has_Estoque_Produto1`
    FOREIGN KEY (`fk_idProduct`)
    REFERENCES `e_commerce_ref`.`Produtos` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_Estoque_Estoque1`
    FOREIGN KEY (`fk_idStorage`)
    REFERENCES `e_commerce_ref`.`Estoques` (`idStorage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e_commerce_ref`.`Pedidos/Produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e_commerce_ref`.`Pedidos/Produtos` (
  `fk_idProduct` INT NOT NULL COMMENT 'Chave estrangeira da tabela de produtos.',
  `fk_idOrder` INT NOT NULL COMMENT 'Chave estrangeira da tabela de pedidos.',
  `Quantidade` INT NULL DEFAULT 1 COMMENT 'Quantidade em estoque, padrão 1.',
  `Status` ENUM('Disponível', 'Sem estoque') NOT NULL DEFAULT 'Disponível' COMMENT 'Status se produto está disponível ou sem estoque.',
  PRIMARY KEY (`fk_idProduct`, `fk_idOrder`),
  INDEX `fk_Produto_has_Pedido_Pedido1_idx` (`fk_idOrder` ASC) VISIBLE,
  INDEX `fk_Produto_has_Pedido_Produto1_idx` (`fk_idProduct` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_has_Pedido_Produto1`
    FOREIGN KEY (`fk_idProduct`)
    REFERENCES `e_commerce_ref`.`Produtos` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_Pedido_Pedido1`
    FOREIGN KEY (`fk_idOrder`)
    REFERENCES `e_commerce_ref`.`Pedidos` (`idOrder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e_commerce_ref`.`Terceiros/ Vendedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e_commerce_ref`.`Terceiros/ Vendedores` (
  `idSeller` INT NOT NULL AUTO_INCREMENT COMMENT 'Id do venderor - auto incremento - chave primária.',
  `SocialName` VARCHAR(255) NOT NULL COMMENT 'Razão Social do vendedor, tipo não nulo.',
  `AbstName` VARCHAR(255) NULL COMMENT 'Nome Fantasia - opcional.',
  `CNPJ` CHAR(15) NULL COMMENT 'CNPJ tipo unico.',
  `CPF` CHAR(11) NULL COMMENT 'CPF - tipo unico.',
  `Local` VARCHAR(255) NOT NULL COMMENT 'Endereço - não pode ser nulo.',
  `Contact` CHAR(11) NOT NULL COMMENT 'Telefonde de contato - Não pode ser nulo.',
  PRIMARY KEY (`idSeller`),
  UNIQUE INDEX `CNPJ_UNIQUE` (`CNPJ` ASC) VISIBLE,
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e_commerce_ref`.`Produtos/Terceiros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e_commerce_ref`.`Produtos/Terceiros` (
  `fk_idSeller` INT NOT NULL COMMENT 'Chave estrangeira da tabela vendedores.',
  `fk_idProduct` INT NOT NULL COMMENT 'Chave estrangeira da tabela produtos.',
  `Quantity` INT NULL DEFAULT 1,
  PRIMARY KEY (`fk_idSeller`, `fk_idProduct`),
  INDEX `fk_Terceiros - Vendedor_has_Relação de Produto/Pedido_Rel_idx` (`fk_idProduct` ASC) VISIBLE,
  INDEX `fk_Terceiros - Vendedor_has_Relação de Produto/Pedido_Ter_idx` (`fk_idSeller` ASC) VISIBLE,
  CONSTRAINT `fk_Terceiros - Vendedor_has_Relação de Produto/Pedido_Terce1`
    FOREIGN KEY (`fk_idSeller`)
    REFERENCES `e_commerce_ref`.`Terceiros/ Vendedores` (`idSeller`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Terceiros - Vendedor_has_Relação de Produto/Pedido_Rela1`
    FOREIGN KEY (`fk_idProduct`)
    REFERENCES `e_commerce_ref`.`Pedidos/Produtos` (`fk_idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e_commerce_ref`.`Documentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e_commerce_ref`.`Documentos` (
  `idDoc` INT NOT NULL AUTO_INCREMENT COMMENT 'id do tipo de documento do cliente.',
  `DocType` ENUM('CPF', 'CNPJ') NOT NULL DEFAULT 'CPF' COMMENT 'Tipo do documento, pode ser \'CPF\' ou \'CNPJ\'.',
  `DocNum` VARCHAR(15) NOT NULL COMMENT 'O número do documento pode ser CPF ou CNPJ tipo varchar(14) tipo unico.',
  `fk_idClient` INT NOT NULL COMMENT 'Chave estrangeira da tabela cliente.',
  PRIMARY KEY (`idDoc`, `fk_idClient`),
  INDEX `fk_Documentos_Cliente1_idx` (`fk_idClient` ASC) VISIBLE,
  UNIQUE INDEX `DocNum_UNIQUE` (`DocNum` ASC) VISIBLE,
  CONSTRAINT `fk_Documentos_Cliente1`
    FOREIGN KEY (`fk_idClient`)
    REFERENCES `e_commerce_ref`.`Clientes` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
